apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5
  labels:
    app: project5
  namespace: default
spec:
  selector:
    matchLabels:
      app: project5
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project5
    spec:
      containers:
      - name: project5
        image: sritchie1305/project5:$CIRCLE_WORKFLOW_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project5
  labels:
    name: project5
spec:
  selector:
    app: project5
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80